[project]
name = "backend-as"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Taijer97", email = "dj.taijer@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
backend-as = "backend_as:main"

[build-system]
requires = ["uv_build>=0.12.8,<0.13.0"]
build-backend = "uv_build"
